#!/bin/bash

set -e

if [[ -n "${STACTOOLS_DEBUG}" ]]; then
    set -x
fi

set -a # export all variables
source docker_env
set +a

function usage() {

    echo -n \
        "Usage: $(basename "$0")
Build stactools containers. Must be run from the repository root

Options:
--pull    Attempt to pull upstream images before building
"
}

while [[ $# -gt 0 ]]
do
    key="$1"
    case $key in
        --help)
        usage
        exit 0
        shift
        ;;

        --pull)
        PULL="--pull"
        shift
        ;;
    esac
done

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        docker build $PULL \
            --build-arg DOCKER_WORKDIR \
            -t stactools-${DOCKER_REPO}-script-runner \
            -f docker/Dockerfile-script-runner .
        STACTOOLS_VERSION=$(docker/run-script python scripts/stactools-version.py)
        echo "Building with stactools version $STACTOOLS_VERSION"
        docker build $PULL \
            --build-arg STACTOOLS_VERSION \
            --build-arg DOCKER_WORKDIR \
            --build-arg DOCKER_NAMESPACE_PACKAGE_DIR \
            -t $DOCKER_REGISTRY/$DOCKER_ORG/$DOCKER_REPO:$DOCKER_TAG \
            -f docker/Dockerfile .
        docker build $PULL \
            --build-arg STACTOOLS_VERSION \
            --build-arg DOCKER_WORKDIR \
            --build-arg DOCKER_NAMESPACE_PACKAGE_DIR \
            -t $DOCKER_REGISTRY/$DOCKER_ORG/$DOCKER_REPO:$DOCKER_TAG_DEV \
            -f docker/Dockerfile-dev .
    fi
    exit
fi
