#!/bin/bash

set -e

if [[ -n "${STACTOOLS_DEBUG}" ]]; then
    set -x
fi

source docker_env

function usage() {

    echo -n \
        "Usage: $(basename "$0") script params
Run a script inside a python docker image
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        docker run --rm \
            -v $(pwd):$DOCKER_WORKDIR \
            stactools-${DOCKER_REPO}-script-runner "$@"
    fi
    exit
fi
